# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7020ea306ed1ecf31cc73f8b044be64e50772b59ee6610cbcd6b0d4a34f25ffc0484111c000d97a31dfe760b79ef7f61a6f5df4ac66fd0c6ecfb72eccbc558b0

test:
  secret_key_base: 261b704497d5ff3af2e9b9528d634b90d7feb112ffce4106ed7e5ddfc6106911e144391997164e609b2f504d29d93e577f20153ddfb0a976feeb2d80dfa35987

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
